<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.Trailers4Jellyfin</RootNamespace>
    <AssemblyVersion>2.0.18.5</AssemblyVersion>
    <FileVersion>2.0.18.5</FileVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" />
    <PackageReference Include="YoutubeExplode" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\config.html" />
    <EmbeddedResource Include="Configuration\config.html" />
  </ItemGroup>

</Project>
